/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:554f3554-cef0-4ec4-bf80-e0e4fa6d4e44",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_hDBMg5HI1",
    "aws_user_pools_web_client_id": "1132dv507m93cg540893g18jiv",
    "oauth": {}
};


export default awsmobile;
